apiVersion: v1
kind: Service
metadata:
  name: {{ include "mkdocs-mcp.fullname" . }}
  labels: {{- include "mkdocs-mcp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "mkdocs-mcp.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
